In [1]:
import os
import re
import pandas as pd
import numpy as np
from nltk.sentiment import SentimentIntensityAnalyzer
from nltk.tokenize import sent_tokenize
import nltk

nltk.download("punkt")
nltk.download("vader_lexicon")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\vetri\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\vetri\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [2]:
sia = SentimentIntensityAnalyzer()

In [3]:
def clean_text(text):
    if pd.isna(text):
        return ""
    
    text = str(text)
    text = re.sub(r"http\S+|www\S+", " ", text)   # remove links
    text = re.sub(r"<.*?>", " ", text)            # remove html
    text = re.sub(r"\s+", " ", text).strip()      # remove extra spaces
    
    return text

In [5]:
def clean_text(text):
    if pd.isna(text):
        return ""
    
    text = str(text)
    
    # remove urls
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)
    
    # remove reddit style remnants if any
    text = re.sub(r"/r/\w+", " ", text)
    text = re.sub(r"/u/\w+", " ", text)
    
    # remove HTML entities
    text = text.replace("&amp;", "and")
    text = text.replace("&lt;", " ")
    text = text.replace("&gt;", " ")
    text = text.replace("&quot;", " ")
    
    # remove extra non-text symbols but keep sentence punctuation
    text = re.sub(r"[^A-Za-z0-9.,!?;:'\"()\-\s]", " ", text)
    
    # collapse repeated punctuation
    text = re.sub(r"([.,!?;]){2,}", r"\1", text)
    
    # collapse spaces
    text = re.sub(r"\s+", " ", text).strip()
    
    return text

In [8]:
def fix_broken_contractions(text):
    contractions = {
        r"\bi m\b": "i'm",
        r"\bdon t\b": "don't",
        r"\bcan t\b": "can't",
        r"\bwon t\b": "won't",
        r"\bisn t\b": "isn't",
        r"\baren t\b": "aren't",
        r"\bwasn t\b": "wasn't",
        r"\bweren t\b": "weren't",
        r"\bshouldn t\b": "shouldn't",
        r"\bcouldn t\b": "couldn't",
        r"\bwouldn t\b": "wouldn't",
        r"\bdidn t\b": "didn't",
        r"\bdoesn t\b": "doesn't",
        r"\bhaven t\b": "haven't",
        r"\bhasn t\b": "hasn't",
        r"\bhadn t\b": "hadn't",
        r"\bit s\b": "it's",
        r"\bthat s\b": "that's",
        r"\bthere s\b": "there's",
        r"\bwhat s\b": "what's",
        r"\bwho s\b": "who's",
        r"\byou re\b": "you're",
        r"\bwe re\b": "we're",
        r"\bthey re\b": "they're",
        r"\bi ve\b": "i've",
        r"\bwe ve\b": "we've",
        r"\bthey ve\b": "they've",
        r"\bi ll\b": "i'll",
        r"\byou ll\b": "you'll",
        r"\bhe s\b": "he's",
        r"\bshe s\b": "she's",
        r"\bi d\b": "i'd",
        r"\byou d\b": "you'd",
        r"\bdoesnt\b": "doesn't",
        r"\bdont\b": "don't",
        r"\bcant\b": "can't",
        r"\bwont\b": "won't",
        r"\bisnt\b": "isn't",
        r"\barent\b": "aren't"
    }
    
    text = text.lower()
    for pattern, replacement in contractions.items():
        text = re.sub(pattern, replacement, text)
    
    return text

In [9]:
def is_useful_text(text, min_chars=30):
    if not text or pd.isna(text):
        return False
    
    text = str(text).strip()
    
    if len(text) < min_chars:
        return False
    
    if len(text.split()) < 6:
        return False
    
    return True

In [10]:
possible_text_columns = [
    "combined_text",
    "review_text",
    "cleaned_review_text",
    "text",
    "body",
    "comment",
    "review",
    "content",
    "description"
]

possible_title_columns = [
    "review_title",
    "title",
    "headline",
    "summary"
]

possible_laptop_columns = [
    "laptop_name",
    "product_name",
    "model_name",
    "name"
]

def choose_column(df, candidates):
    for col in candidates:
        if col in df.columns:
            return col
    return None

In [12]:
for filename in os.listdir(input_folder):
    if filename.endswith(".csv"):
        file_path = os.path.join(input_folder, filename)
        try:
            df = pd.read_csv(file_path)
            print(f"\n{filename}")
            print(df.columns.tolist())
        except Exception as e:
            print(f"Error in {filename}: {e}")

ASUS_ROG_Strix_G15.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

ASUS_ROG_Strix_Scar_15_.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

ASUS_ROG_Zephyrus_G14,.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

ASUS_TUF_A15_.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

ASUS_TUF_F15_Gaming_Laptop,_.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

ASUS_TUF_Gaming_F15_.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

ASUS_Vivobook_15.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

ASUS_Vivobook_16.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

ASUS_Vivobook_Go_.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

ASUS_Zenbook_14.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Dell_Alienware_m16_R2.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Dell_G16_.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Dell_G_Series.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Dell_Inspiron_3520_Laptop.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Dell_Inspiron_5430.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Dell_Inspiron_7430.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Dell_SmartChoice_G15,_13th_.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Dell_SmartChoice_G15.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Dell_Vostro_3530.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

HP_15s,eq series.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

HP_15s.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

HP_OMEN_17_Gaming_Laptop_2024,.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

HP_OMEN_Transcend_14.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

HP_Pavilion_15_.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

HP_Pavilion_Aero_.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

HP_Smartchoice_Omen.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

HP_Smartchoice_Victus.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

HP_Smartchoice_Victus_g4.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

HP_Victus_16-.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Lenovo_IdeaPad_3.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Lenovo_IdeaPad_Gaming_3.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Lenovo_IdeaPad_Slim_3.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Lenovo_IdeaPad_Slim_5_.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Lenovo_Legion_5.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Lenovo_Legion_Pro_7_2025_Intel_Core_Ultra_9_275HX__NVIDIA_RTX_5080_16GB_(32GB_RAM1TB_SSDWQXGA_OLED240Hz16_(40.6cm)Windows_11Office_2024+AI_NowBlack2.5Kg),_83F500D9IN_AI_Powered_Gaming_Laptop_amazon_aspect_sentiment.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Lenovo_Legion_Slim_7_.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Lenovo_LOQ_.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Lenovo_LOQ_g4.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

Lenovo_Yoga_Slim_6_.csv
['laptop_name', 'sentence', 'aspect', 'sentiment', 'compound_score']

In [11]:
input_folder = r"amazon_dataset"
cleaned_folder = r"amazon_cleaned_dataset"

os.makedirs(cleaned_folder, exist_ok=True)

for filename in os.listdir(input_folder):
    if not filename.endswith(".csv"):
        continue
    
    file_path = os.path.join(input_folder, filename)
    
    try:
        df = pd.read_csv(file_path)
        print(f"\nProcessing: {filename}")
        print("Original rows:", len(df))
        
        text_col = choose_column(df, possible_text_columns)
        title_col = choose_column(df, possible_title_columns)
        laptop_col = choose_column(df, possible_laptop_columns)
        
        if text_col is None and title_col is None:
            print("No usable review/title column found. Skipping.")
            continue
        
        # build combined text
        if title_col and text_col:
            df["combined_text"] = (
                df[title_col].fillna("").astype(str).str.strip() + ". " +
                df[text_col].fillna("").astype(str).str.strip()
            ).str.strip()
        elif text_col:
            df["combined_text"] = df[text_col].fillna("").astype(str).str.strip()
        elif title_col:
            df["combined_text"] = df[title_col].fillna("").astype(str).str.strip()
        
        # laptop name
        if laptop_col:
            clean_df = df[[laptop_col, "combined_text"]].copy()
            clean_df.columns = ["laptop_name", "raw_text"]
        else:
            clean_df = df[["combined_text"]].copy()
            clean_df.columns = ["raw_text"]
            clean_df["laptop_name"] = filename.replace(".csv", "")
            clean_df = clean_df[["laptop_name", "raw_text"]]
        
        # clean text
        clean_df["cleaned_text"] = clean_df["raw_text"].astype(str).apply(clean_text)
        clean_df["cleaned_text"] = clean_df["cleaned_text"].apply(fix_broken_contractions)
        
        # remove useless rows
        clean_df = clean_df[clean_df["cleaned_text"].apply(is_useful_text)]
        
        # drop duplicates
        clean_df = clean_df.drop_duplicates(subset=["cleaned_text"]).reset_index(drop=True)
        
        # keep final columns
        clean_df = clean_df[["laptop_name", "cleaned_text"]]
        
        output_path = os.path.join(cleaned_folder, filename)
        clean_df.to_csv(output_path, index=False, encoding="utf-8")
        
        print("Cleaned rows:", len(clean_df))
        print("Saved to:", output_path)
    
    except Exception as e:
        print(f"Error in {filename}: {e}")

Processing: ASUS_ROG_Strix_G15.csv
Original rows: 6
No usable review/title column found. Skipping.

Processing: ASUS_ROG_Strix_Scar_15_.csv
Original rows: 7
No usable review/title column found. Skipping.

Processing: ASUS_ROG_Zephyrus_G14,.csv
Original rows: 8
No usable review/title column found. Skipping.

Processing: ASUS_TUF_A15_.csv
Original rows: 328
No usable review/title column found. Skipping.

Processing: ASUS_TUF_F15_Gaming_Laptop,_.csv
Original rows: 252
No usable review/title column found. Skipping.

Processing: ASUS_TUF_Gaming_F15_.csv
Original rows: 222
No usable review/title column found. Skipping.

Processing: ASUS_Vivobook_15.csv
Original rows: 220
No usable review/title column found. Skipping.

Processing: ASUS_Vivobook_16.csv
Original rows: 220
No usable review/title column found. Skipping.

Processing: ASUS_Vivobook_Go_.csv
Original rows: 327
No usable review/title column found. Skipping.

Processing: ASUS_Zenbook_14.csv
Original rows: 51
No usable review/title column found. Skipping.

Processing: Dell_Alienware_m16_R2.csv
Original rows: 42
No usable review/title column found. Skipping.

Processing: Dell_G16_.csv
Original rows: 0
No usable review/title column found. Skipping.

Processing: Dell_G_Series.csv
Original rows: 484
No usable review/title column found. Skipping.

Processing: Dell_Inspiron_3520_Laptop.csv
Original rows: 48
No usable review/title column found. Skipping.

Processing: Dell_Inspiron_5430.csv
Original rows: 58
No usable review/title column found. Skipping.

Processing: Dell_Inspiron_7430.csv
Original rows: 25
No usable review/title column found. Skipping.

Processing: Dell_SmartChoice_G15,_13th_.csv
Original rows: 571
No usable review/title column found. Skipping.

Processing: Dell_SmartChoice_G15.csv
Original rows: 571
No usable review/title column found. Skipping.

Processing: Dell_Vostro_3530.csv
Original rows: 3
No usable review/title column found. Skipping.

Processing: HP_15s,eq series.csv
Original rows: 265
No usable review/title column found. Skipping.

Processing: HP_15s.csv
Original rows: 185
No usable review/title column found. Skipping.

Processing: HP_OMEN_17_Gaming_Laptop_2024,.csv
Original rows: 103
No usable review/title column found. Skipping.

Processing: HP_OMEN_Transcend_14.csv
Original rows: 1
No usable review/title column found. Skipping.

Processing: HP_Pavilion_15_.csv
Original rows: 188
No usable review/title column found. Skipping.

Processing: HP_Pavilion_Aero_.csv
Original rows: 237
No usable review/title column found. Skipping.

Processing: HP_Smartchoice_Omen.csv
Original rows: 274
No usable review/title column found. Skipping.

Processing: HP_Smartchoice_Victus.csv
Original rows: 224
No usable review/title column found. Skipping.

Processing: HP_Smartchoice_Victus_g4.csv
Original rows: 102
No usable review/title column found. Skipping.

Processing: HP_Victus_16-.csv
Original rows: 0
No usable review/title column found. Skipping.

Processing: Lenovo_IdeaPad_3.csv
Original rows: 18
No usable review/title column found. Skipping.

Processing: Lenovo_IdeaPad_Gaming_3.csv
Original rows: 15
No usable review/title column found. Skipping.

Processing: Lenovo_IdeaPad_Slim_3.csv
Original rows: 2
No usable review/title column found. Skipping.

Processing: Lenovo_IdeaPad_Slim_5_.csv
Original rows: 82
No usable review/title column found. Skipping.

Processing: Lenovo_Legion_5.csv
Original rows: 10
No usable review/title column found. Skipping.

Processing: Lenovo_Legion_Pro_7_2025_Intel_Core_Ultra_9_275HX__NVIDIA_RTX_5080_16GB_(32GB_RAM1TB_SSDWQXGA_OLED240Hz16_(40.6cm)Windows_11Office_2024+AI_NowBlack2.5Kg),_83F500D9IN_AI_Powered_Gaming_Laptop_amazon_aspect_sentiment.csv
Original rows: 4
No usable review/title column found. Skipping.

Processing: Lenovo_Legion_Slim_7_.csv
Original rows: 18
No usable review/title column found. Skipping.

Processing: Lenovo_LOQ_.csv
Original rows: 190
No usable review/title column found. Skipping.

Processing: Lenovo_LOQ_g4.csv
Original rows: 116
No usable review/title column found. Skipping.

Processing: Lenovo_Yoga_Slim_6_.csv
Original rows: 6
No usable review/title column found. Skipping.

In [6]:
def detect_aspect(sentence):
    sentence = sentence.lower()

    aspect_keywords = {
        "performance": [
            "performance", "fast", "speed", "smooth", "lag", "gaming",
            "processor", "cpu", "amd", "intel", "fps", "powerful"
        ],
        "battery": [
            "battery", "backup", "charging", "charge", "drain"
        ],
        "display": [
            "display", "screen", "brightness", "refresh", "resolution",
            "fhd", "144hz", "panel"
        ],
        "price": [
            "price", "cost", "expensive", "cheap", "value", "money", "deal", "worth"
        ],
        "design": [
            "design", "build", "look", "stylish", "weight", "portable",
            "body", "plastic", "premium"
        ],
        "keyboard": [
            "keyboard", "keys", "typing", "trackpad", "touchpad"
        ],
        "audio": [
            "speaker", "speakers", "audio", "sound", "mic"
        ],
        "camera": [
            "camera", "webcam"
        ],
        "thermal": [
            "heat", "heating", "temperature", "thermal", "fan", "cooling", "hot"
        ],
        "storage": [
            "ssd", "hdd", "storage"
        ],
        "ram": [
            "ram", "memory"
        ],
        "graphics": [
            "gpu", "graphics", "rtx", "gtx", "nvidia"
        ]
    }

    for aspect, keywords in aspect_keywords.items():
        for word in keywords:
            if word in sentence:
                return aspect

    return "other"

In [7]:
def get_sentiment(sentence):
    score = sia.polarity_scores(sentence)["compound"]

    if score >= 0.05:
        sentiment = "positive"
    elif score <= -0.05:
        sentiment = "negative"
    else:
        sentiment = "neutral"

    return sentiment, score

In [14]:
sentiment_folder = r"amazon_dataset"
summary_rows = []

for filename in os.listdir(sentiment_folder):
    if not filename.endswith(".csv"):
        continue
    
    file_path = os.path.join(sentiment_folder, filename)
    df = pd.read_csv(file_path)
    
    positive_count = (df["sentiment"] == "positive").sum()
    negative_count = (df["sentiment"] == "negative").sum()
    neutral_count = (df["sentiment"] == "neutral").sum()
    
    summary_rows.append({
        "file_name": filename,
        "positive_sentences": positive_count,
        "negative_sentences": negative_count,
        "neutral_sentences": neutral_count,
        "total_sentences": len(df)
    })

summary_df = pd.DataFrame(summary_rows)
summary_df.to_csv("reddit_vader_summary.csv", index=False)
summary_df

,file_name,positive_sentences,negative_sentences,neutral_sentences,total_sentences
0,ASUS_ROG_Strix_G15.csv,5,0,1,6
1,ASUS_ROG_Strix_Scar_15_.csv,5,1,1,7
2,"ASUS_ROG_Zephyrus_G14,.csv",8,0,0,8
3,ASUS_TUF_A15_.csv,227,47,54,328
4,"ASUS_TUF_F15_Gaming_Laptop,_.csv",136,82,34,252
5,ASUS_TUF_Gaming_F15_.csv,120,39,63,222
6,ASUS_Vivobook_15.csv,151,36,33,220
7,ASUS_Vivobook_16.csv,151,36,33,220
8,ASUS_Vivobook_Go_.csv,191,49,87,327
9,ASUS_Zenbook_14.csv,34,4,13,51
10,Dell_Alienware_m16_R2.csv,25,7,10,42
11,Dell_G16_.csv,0,0,0,0
12,Dell_G_Series.csv,293,77,114,484
13,Dell_Inspiron_3520_Laptop.csv,25,14,9,48
14,Dell_Inspiron_5430.csv,40,5,13,58
15,Dell_Inspiron_7430.csv,15,4,6,25
16,"Dell_SmartChoice_G15,_13th_.csv",356,86,129,571
17,Dell_SmartChoice_G15.csv,356,86,129,571
18,Dell_Vostro_3530.csv,1,1,1,3
19,"HP_15s,eq series.csv",136,63,66,265
20,HP_15s.csv,119,36,30,185
21,"HP_OMEN_17_Gaming_Laptop_2024,.csv",61,18,24,103
22,HP_OMEN_Transcend_14.csv,1,0,0,1
23,HP_Pavilion_15_.csv,133,23,32,188
24,HP_Pavilion_Aero_.csv,130,29,78,237
25,HP_Smartchoice_Omen.csv,168,56,50,274
26,HP_Smartchoice_Victus.csv,136,43,45,224
27,HP_Smartchoice_Victus_g4.csv,72,9,21,102
28,HP_Victus_16-.csv,0,0,0,0
29,Lenovo_IdeaPad_3.csv,3,6,9,18
30,Lenovo_IdeaPad_Gaming_3.csv,8,6,1,15
31,Lenovo_IdeaPad_Slim_3.csv,2,0,0,2
32,Lenovo_IdeaPad_Slim_5_.csv,60,11,11,82
33,Lenovo_Legion_5.csv,9,1,0,10
34,Lenovo_Legion_Pro_7_2025_Intel_Core_Ultra_9_27...,4,0,0,4
35,Lenovo_Legion_Slim_7_.csv,16,2,0,18
36,Lenovo_LOQ_.csv,125,31,34,190
37,Lenovo_LOQ_g4.csv,66,18,32,116
38,Lenovo_Yoga_Slim_6_.csv,3,3,0,6

In [16]:
import os
import pandas as pd

input_folder = r"amazon_dataset"   # folder where your amazon csv files are stored

dfs = []

for filename in os.listdir(input_folder):
    if filename.endswith(".csv"):
        file_path = os.path.join(input_folder, filename)
        df = pd.read_csv(file_path)
        dfs.append(df)

combined_df = pd.concat(dfs, ignore_index=True)

print("Total rows:", len(combined_df))
combined_df.head()

Total rows: 5483

C:\Users\vetri\AppData\Local\Temp\ipykernel_15316\69922483.py:14: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat(dfs, ignore_index=True)

,laptop_name,sentence,aspect,sentiment,compound_score
0,"ASUS ROG Strix G15, AMD Ryzen 7 6800H, 15.6""(3...",It's value of money for a 3050 graphic card an...,performance,positive,0.7543
1,"ASUS ROG Strix G15, AMD Ryzen 7 6800H, 15.6""(3...",It's value of money for a 3050 graphic card an...,display,positive,0.7543
2,"ASUS ROG Strix G15, AMD Ryzen 7 6800H, 15.6""(3...",It's value of money for a 3050 graphic card an...,price,positive,0.7543
3,"ASUS ROG Strix G15, AMD Ryzen 7 6800H, 15.6""(3...",And it's brightness is customisable too.,display,positive,0.3818
4,"ASUS ROG Strix G15, AMD Ryzen 7 6800H, 15.6""(3...",This is my first gaming laptop!,performance,neutral,0.0000

In [17]:
aspect_pivot = pd.pivot_table(
    combined_df,
    index=["laptop_name", "aspect"],
    columns="sentiment",
    aggfunc="size",
    fill_value=0
)

In [18]:
aspect_pivot["total_mentions"] = (
    aspect_pivot["positive"] +
    aspect_pivot["negative"] +
    aspect_pivot["neutral"]
)

In [19]:
aspect_pivot["aspect_score"] = (
    aspect_pivot["positive"] -
    aspect_pivot["negative"]
) / aspect_pivot["total_mentions"]

aspect_pivot

sentiment                                                         negative  \
laptop_name                                        aspect
ASUS ROG Strix G15, AMD Ryzen 7 6800H, 15.6"(39... display               0
                                                   performance           0
                                                   price                 0
ASUS ROG Strix Scar 15 (2022), Intel Core i9-12... build_quality         0
                                                   design                0
...                                                                    ...
Lenovo Legion Slim 7 Intel Core i7-13700H 16" (... thermals              1
Lenovo Yoga Slim 6 13th Gen Intel Evo Core i5 1... audio                 3
                                                   design                0
                                                   display               0
                                                   software              0

sentiment                                                         neutral  \
laptop_name                                        aspect
ASUS ROG Strix G15, AMD Ryzen 7 6800H, 15.6"(39... display              0
                                                   performance          1
                                                   price                0
ASUS ROG Strix Scar 15 (2022), Intel Core i9-12... build_quality        0
                                                   design               0
...                                                                   ...
Lenovo Legion Slim 7 Intel Core i7-13700H 16" (... thermals             0
Lenovo Yoga Slim 6 13th Gen Intel Evo Core i5 1... audio                0
                                                   design               0
                                                   display              0
                                                   software             0

sentiment                                                         positive  \
laptop_name                                        aspect
ASUS ROG Strix G15, AMD Ryzen 7 6800H, 15.6"(39... display               2
                                                   performance           2
                                                   price                 1
ASUS ROG Strix Scar 15 (2022), Intel Core i9-12... build_quality         1
                                                   design                1
...                                                                    ...
Lenovo Legion Slim 7 Intel Core i7-13700H 16" (... thermals              2
Lenovo Yoga Slim 6 13th Gen Intel Evo Core i5 1... audio                 0
                                                   design                1
                                                   display               1
                                                   software              1

sentiment                                                         total_mentions  \
laptop_name                                        aspect
ASUS ROG Strix G15, AMD Ryzen 7 6800H, 15.6"(39... display                     2
                                                   performance                 3
                                                   price                       1
ASUS ROG Strix Scar 15 (2022), Intel Core i9-12... build_quality               1
                                                   design                      1
...                                                                          ...
Lenovo Legion Slim 7 Intel Core i7-13700H 16" (... thermals                    3
Lenovo Yoga Slim 6 13th Gen Intel Evo Core i5 1... audio                       3
                                                   design                      1
                                                   display                     1
                                                   software                    1

sentiment                                                         aspect_score
laptop_name                                        aspect
ASUS ROG Strix G15, AMD Ryzen 7 6800H, 15.6"(39... display            1.000000
                                                   performance        0.666667
                                                   price              1.000000
ASUS ROG Strix Scar 15 (2022), Intel Core i9-12... build_quality      1.000000
                                                   design             1.000000
...                                                                        ...
Lenovo Legion Slim 7 Intel Core i7-13700H 16" (... thermals           0.333333
Lenovo Yoga Slim 6 13th Gen Intel Evo Core i5 1... audio             -1.000000
                                                   design             1.000000
                                                   display            1.000000
                                                   software           1.000000

[348 rows x 5 columns]

In [20]:
battery_comparison = aspect_pivot.xs("battery", level="aspect")

battery_comparison.sort_values("aspect_score", ascending=False)

sentiment,negative,neutral,positive,total_mentions,aspect_score
laptop_name,,,,,
"ASUS ROG Zephyrus G14,AMD Ryzen 9 270, Gaming Laptop(RTX 5060-8GB/90W TGP/16GB/1TB/3K OLED/14/120Hz/73WHrs/Windows 11/M365 Basic (1Year)*/Office Home 2024/Eclipse Gray/1.5 Kg) GA403UM-QS007WS",0,0,1,1,1.000000
"Dell Alienware m16 R2, Intel Core Ultra 9-185H, NVIDIA GeForce RTX 4070-8GB, 16GB RAM, 1TB SSD, QHD+ 16""/40.6cm, Windows 11, Dark Metallic Moon, 2.61Kg, AlienFX RGB Backlit KB, 240Hz AI Powered Laptop",0,0,1,1,1.000000
"Dell Inspiron 5430, Intel Core i5-1335U, 13th Gen, 8GB LPDDR5, 512GB SSD, FHD 14""/35.56cm, Windows 11, MS Office 21, Platinum Silver, 1.59KG, Backlit KB, Thunderbolt 4.0 Port, McAfee 15 Months Laptop",0,0,2,2,1.000000
"Lenovo Legion Slim 7 Intel Core i7-13700H 16"" (40.64cm) 3.2K IPS 165Hz 430Nits Gaming Laptop (16GB/1TB SSD/Win 11/Office 2021/NVIDIA RTX 4060 8GB/Alexa/3 Month Game Pass/Storm Grey/2Kg),82Y3006XIN",0,0,2,2,1.000000
"Lenovo Legion Pro 7 2025 Intel Core Ultra 9 275HX | NVIDIA RTX 5080 16GB (32GB RAM/1TB SSD/WQXGA OLED/240Hz/16 (40.6cm)/Windows 11/Office 2024+AI Now/Black/2.5Kg), 83F500D9IN AI Powered Gaming Laptop",0,0,1,1,1.000000
"Lenovo IdeaPad Slim 5 12th Gen Intel Core i5 12450H 16"" (40.6cm) WUXGA IPS 300Nits Laptop (16GB/512GB SSD/Win 11/Office 2021/Backlit KB/FHD 1080p Camera/Alexa/3 Month Game Pass/Grey/1.8Kg), 83BG000DIN",0,1,3,4,0.750000
"ASUS Zenbook 14, Smartchoice,AMD Ryzen AI 5 340, AI PC(AMD Radeon Graphics/16GB RAM/512GB SSD/3K OLED/14/120Hz/Windows 11/M365 Basic (1Year)*/Office Home 2024/Jade Black/1.2 Kg) UM3406KA-PP240WS",0,2,5,7,0.714286
"HP Smartchoice Victus, 13th Gen i7-13620H, 6GB RTX 4050, 16GB DDR4(Upgradeable) 512GB SSD, 144Hz, 300nits, FHD, 15.6''/39.6cm, Win11, M365* Office24, Mica Silver, 2.3kg, fa2100/03/04tx, Gaming Laptop",2,2,14,18,0.666667
"HP Pavilion Aero AMD Ryzen 5-16Gb Ram/512Gb Ssd 13.3 Inches (33.8 Cm) Wuxga Ultra Thin and Light, 970 Gm,400 Nits Anti-Glare Srgb Display/B&O Audio/Alexa/Fpr/Backlit Kb/Windows 11 Ready, 13-Be0030Au",0,7,11,18,0.611111
"ASUS Vivobook Go 15.6” Slim Laptop, AMD Ryzen 5 7520U, 8GB, 512GB, Windows 11 Home, Cool Silver, Military Grade Durability, Fast Charging, Webcam Shield, E1504FA-AS54",2,5,10,17,0.470588
"HP Smartchoice Omen AMD Ryzen 7 7840Hs, 8GB RTX 4060 (16GB DDR5, 1TB SSD) FHD, 165Hz, 300Nits, IPS, 16.1''/40.9cm, Win11, Office 21, Black, 2.32kg, Xd0020ax, RGB kb, Tempest Cooling, AI Gaming Laptop",5,4,13,22,0.363636
"Lenovo IdeaPad Gaming 3 12th Gen Intel Core i5 12450H 15.6"" (39.62cm) FHD IPS 120Hz Gaming Laptop (16GB/512GB SSD/Win11/Office 21/NVIDIA RTX 3050 4GB/Alexa/3 Mon Game Pass/Onyx Grey/2.3Kg), 82S9017TIN",1,0,2,3,0.333333
"ASUS Vivobook 15, Smartchoice,Intel Core i5 13th Gen 13420H,16GB RAM, 512GB SSD, FHD 15.6"",Windows 11, Office Home 2024, Quiet Blue, 1.70 kg, X1502VA-BQ836WS,Intel UHD iGPU, M365 Basic (1Year)* Laptop",8,6,17,31,0.290323
"ASUS Vivobook 16, 13th Gen, Intel Core i5-13420H,16GB RAM,512GB SSD,FHD (1920 x 1200) OLED,Win 11,M365 Basic (1Year)*,Backlit Keyboard,Office 2024,Silver,1.88 kg,X1605VA-SH1952WS, Thin & Light Laptop",8,6,17,31,0.290323
"ASUS TUF A15 (2025), AMD Ryzen 7 7445HS,RTX 3050-4GB,75W TGP,16GB DDR5(Upgradeable Upto 64GB) 512GB SSD,FHD,15.6"",144Hz,RGB Keyboard,Windows 11,Graphite Black,2.3 Kg FA506NCG-HN199W, Gaming Laptop",10,16,23,49,0.265306
"HP 15 Pavilion AMD Ryzen 5 7530U, 15.6-inch FHD, 8GB DDR4, 512GB SSD, AMD Radeon Graphics, 720p HD Camera, Backlit KB, Audio by B&O (Win 11 Home, MSO 2021, Silver, 1.75 kg), eh3036AU / EH2050AU",4,4,8,16,0.250000
"HP OMEN 17 Gaming Laptop 2024, 17.3"" 2K QHD IPS 165HZ Display, 13th Gen Intel 24-Core i9-13900HX, 32GB DDR5 RAM, 1TB SSD, GeForce RTX 4080, Backlit, Microsoft Office Lifetime License & Windows 11 Pro",6,3,10,19,0.210526
"HP 15s- 11th Gen Intel Core i5-8GB RAM/512GB SSD/32GB Intel Optane Memory 15.6inch(39.6cm) FHD Laptop (Intel Iris Xe Graphics/Alexa/Dual Speakers/Win 11 Home/Ms Office), 15s- Fq4022TU",8,4,13,25,0.200000
"Lenovo LOQ AMD Ryzen 5 7235HS | NVIDIA RTX 4050 6GB (16GB RAM/512GB SSD/144Hz Refresh Rate/15.6"" (39.6cm)/Windows 11/Office Home 2024/3 Mon. Game Pass/Grey/2.4Kg), 83JC00NYIN AI Gaming Laptop",7,7,12,26,0.192308
"HP 15s, AMD Ryzen 5 5500U (8GB DDR4, 512GB SSD) FHD, Anti-Glare, 15.6''/39.6 cm, Win 11, Office 21, Silver, 1.69 kg, eq2144AU/eq2304AU, AMD Radeon Graphics, HD Camera, Dual Speakers Laptop",6,6,10,22,0.181818
"Lenovo LOQ 2024, 12th Gen Intel Core i5 12450HX, RTX 3050-6GB, 16GB RAM, 512GB SSD, FHD, 15.6""/39.6cm, 144Hz, Windows 11, Office 2024, Grey, 2.4Kg, 83GS00LNIN, 3 Mon. Game Pass, Gaming Laptop",10,4,15,29,0.172414
"Dell G Series, 13th Gen Intel Core i5-13450HX, NVIDIA RTX 3050-6GB, 16GB DDR5, 512GB SSD, FHD, 15.6""/39.62cm, Windows 11, Microsoft Office Home 2024, 2.65KG, G15-5530, Backlit Keyboard, Gaming Laptop",27,29,40,96,0.135417
"Dell SmartChoice G15, 13th Gen Intel Core i5-13450HX, NVIDIA RTX 3050-6GB, (16GB RAM 1TB SSD) FHD 15.6""/39.62 cm, Orange Backlit Keyboard, Windows 11, Microsoft Office Home 2024, 2.65Kg Gaming Laptop",54,58,80,192,0.135417
"HP Smartchoice Victus, 13th Gen Intel Core i5-13420H, 4GB RTX 3050, 16GB DDR4(Upgradeable) 512GB SSD, 144Hz, 300nits, FHD, 15.6’’/39.6cm, Win11, Office24, Blue, 2.29kg, fa2190/fa2191tx Gaming Laptop",8,6,11,25,0.120000
"ASUS TUF F15 Gaming Laptop, Core i5-11400H 11th Gen, 15.6-inch (39.62 cm) FHD 144Hz,(16GB RAM/512GB SSD/4GB NVIDIA GeForce RTX 2050/Windows 11/ RGB Backlit KB/Black/2.30 kg), FX506HF-HN025W",15,6,16,37,0.027027
"ASUS TUF Gaming F15 (2023) Gaming Laptop, 90WHr Battery, Intel Core i7-12700H 12th Gen, 15.6"" FHD 144Hz, 8GB RTX 4060, (16GB RAM/512GB SSD/Windows 11//1-Zone RGB/Gray/2.20 Kg), FX507ZV-LP094W",7,7,7,21,0.000000
"Dell Inspiron 7430 2in1 Touch 13th Gen Laptop, Intel Core i3-1315U Processor, 8GB, 256Gb SSD, 14.0"" (35.56cm) FHD+ Display, Windows 11 + MSO'21, Backlit KB + Finger Print, Silver,Thin & Light- 1.58kg",0,2,0,2,0.000000
"Dell Inspiron 3520 Laptop - 15.6-inch FHD (1920 x 1080) 120Hz Display, Intel Core i5-1235U Processor, 8GB DDR4 RAM, 512GB SSD, WiFi 5, Windows 11 S Mode - Carbon Black",2,1,1,4,-0.250000
"Lenovo IdeaPad 3, Intel Core i3-1215U, 12th Gen, 8GB RAM, 512GB SSD, FHD, 14""/35.5cm, Windows 11, MSOffice 2021, Arctic Grey, 1.43Kg, 82RJ00FUIN, 1 Year Warranty, 3months Game Pass, Thin& Light Laptop",3,1,0,4,-0.750000
"Dell Vostro 3530 Laptop 15.6"" FHD Display, 13th Generation Intel Core i5-1334U Processor, 16GB DDR4 RAM, 512GB SSD, Intel Iris Xe Graphics, Win 11 + Office H&S 2024- Titan Grey, 1.66 Kg",1,0,0,1,-1.000000

In [21]:
import os
import pandas as pd

folder = r"amazon_dataset"

dfs = []

for file in os.listdir(folder):
    if file.endswith(".csv"):
        df = pd.read_csv(os.path.join(folder, file))
        
        df = df[["laptop_name", "sentence", "compound_score", "sentiment"]]
        dfs.append(df)

amazon_final = pd.concat(dfs, ignore_index=True)

amazon_final.to_csv("amazon_final_sentiment.csv", index=False)

print("Saved:", len(amazon_final), "rows")

Saved: 5483 rows

C:\Users\vetri\AppData\Local\Temp\ipykernel_15316\2884166451.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  amazon_final = pd.concat(dfs, ignore_index=True)

In [22]:
import os
import pandas as pd

input_folder = r"amazon_dataset"          # folder with current amazon files
output_folder = r"amazon_final_files"     # new folder for final files

os.makedirs(output_folder, exist_ok=True)

for filename in os.listdir(input_folder):
    if not filename.endswith(".csv"):
        continue

    file_path = os.path.join(input_folder, filename)
    df = pd.read_csv(file_path)

    # keep only required columns
    df = df[["laptop_name", "sentence", "compound_score", "sentiment"]]

    output_path = os.path.join(output_folder, filename)
    df.to_csv(output_path, index=False, encoding="utf-8")

    print(f"Saved: {filename} | Rows: {len(df)}")

Saved: ASUS_ROG_Strix_G15.csv | Rows: 6
Saved: ASUS_ROG_Strix_Scar_15_.csv | Rows: 7
Saved: ASUS_ROG_Zephyrus_G14,.csv | Rows: 8
Saved: ASUS_TUF_A15_.csv | Rows: 328
Saved: ASUS_TUF_F15_Gaming_Laptop,_.csv | Rows: 252
Saved: ASUS_TUF_Gaming_F15_.csv | Rows: 222
Saved: ASUS_Vivobook_15.csv | Rows: 220
Saved: ASUS_Vivobook_16.csv | Rows: 220
Saved: ASUS_Vivobook_Go_.csv | Rows: 327
Saved: ASUS_Zenbook_14.csv | Rows: 51
Saved: Dell_Alienware_m16_R2.csv | Rows: 42
Saved: Dell_G16_.csv | Rows: 0
Saved: Dell_G_Series.csv | Rows: 484
Saved: Dell_Inspiron_3520_Laptop.csv | Rows: 48
Saved: Dell_Inspiron_5430.csv | Rows: 58
Saved: Dell_Inspiron_7430.csv | Rows: 25
Saved: Dell_SmartChoice_G15,_13th_.csv | Rows: 571
Saved: Dell_SmartChoice_G15.csv | Rows: 571
Saved: Dell_Vostro_3530.csv | Rows: 3
Saved: HP_15s,eq series.csv | Rows: 265
Saved: HP_15s.csv | Rows: 185
Saved: HP_OMEN_17_Gaming_Laptop_2024,.csv | Rows: 103
Saved: HP_OMEN_Transcend_14.csv | Rows: 1
Saved: HP_Pavilion_15_.csv | Rows: 188
Saved: HP_Pavilion_Aero_.csv | Rows: 237
Saved: HP_Smartchoice_Omen.csv | Rows: 274
Saved: HP_Smartchoice_Victus.csv | Rows: 224
Saved: HP_Smartchoice_Victus_g4.csv | Rows: 102
Saved: HP_Victus_16-.csv | Rows: 0
Saved: Lenovo_IdeaPad_3.csv | Rows: 18
Saved: Lenovo_IdeaPad_Gaming_3.csv | Rows: 15
Saved: Lenovo_IdeaPad_Slim_3.csv | Rows: 2
Saved: Lenovo_IdeaPad_Slim_5_.csv | Rows: 82
Saved: Lenovo_Legion_5.csv | Rows: 10
Saved: Lenovo_Legion_Pro_7_2025_Intel_Core_Ultra_9_275HX__NVIDIA_RTX_5080_16GB_(32GB_RAM1TB_SSDWQXGA_OLED240Hz16_(40.6cm)Windows_11Office_2024+AI_NowBlack2.5Kg),_83F500D9IN_AI_Powered_Gaming_Laptop_amazon_aspect_sentiment.csv | Rows: 4
Saved: Lenovo_Legion_Slim_7_.csv | Rows: 18
Saved: Lenovo_LOQ_.csv | Rows: 190
Saved: Lenovo_LOQ_g4.csv | Rows: 116
Saved: Lenovo_Yoga_Slim_6_.csv | Rows: 6